### ISSUE TITLE
Look deeper into argparse and Configurator

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#1005]
Passing a list of floats to an application does not work. The work around we have been using (see e.g. `calculate-trigger-rate` application) is to require a list of strings and then convert to a list of floats in the application. Although this works, we need to understand why a list of float does not work in the first place. 

https://github.com/gammasim/simtools/pull/1000#discussion_r1647715407

**Comment by GernotMaier** [comment]
This issue is already addressed in the simulation configuration PR (#989) and I will extract it into a separate PR for easier review.

This is the solution I found after spending quite some time:

- allow for e.g., `--energy_range "10 GeV 50 TeV"`  (only the central space is important, so it can also be `"10GeV 50TeV"`)
- returned a tuples of astropy quantities. The assumption is the the correct unit conversion is applied in the spezialied modules (e.g., in corsika_config, which should know about the required units in corsika)

Not sure if one would prefer `--energy_range 50 GeV 10 TeV` (without quotes), I think we can start with the above and then continue. Definitely the nice part here is that we do not force the units onto the user.

**Comment by VictorBarbosaMartins** [comment]
I agree with the solution you found. And agree also that treating this in a dedicated PR is better too.
