### ISSUE TITLE
Add a CI workflow for docstr-coverage package

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#409]
As discussed before, we would like to have a tool to show us how well the code is documented. The following package seems to be a good choice: https://pypi.org/project/docstr-coverage/ 

A pre-defined github actions already exists in https://github.com/marketplace/actions/docstr-coverage

**Comment by GernotMaier** [comment]
Looking at it: I think what we want is a pre-commit hook, so that we don't commit code without docstrings. It is not about showing that the code is documented, it is about getting the code documented.

I've added this to the `docstr_coverage` branch, but note that commits fails unless one sets the `--fail-under` to a low value. My feeling is that we first have to write code to reach maybe 90% of docstr coverage and then start using the tool?

Minor thing: not available through conda but through pip:
`pip install docstr-coverage`

How would I install this using conda? Or should we add this to setup.py?

**Comment by orelgueta** [comment]
I think you can add an entry to the environment file like
```
pip:
    docstr-coverage
```
and then conda installs it from pip. At least this is something I remember doing at some point. Did not check before writing this comment, so please take with a grain of salt.

And yes, we should probably first increase our coverage before starting to use it.

**Comment by GernotMaier** [comment]
pre-commit hook has been added with #470
