### ISSUE TITLE
Write corsika histograms output in hd5 files instead of ecsv

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#547]
The last point is what was just raised in the meeting. 
We need to consider writing out hd5 files instead of ecsv files. It will probably not require any real changes to the code, just a quick change.

_Originally posted by @orelgueta in https://github.com/gammasim/simtools/pull/492#pullrequestreview-1582319165_

_UPDATE:_ 27.08.2023
**Status now:** 
- At the moment we save corsika output histograms [(generate_corsika_histograms.py)](https://github.com/gammasim/simtools/blob/main/simtools/applications/generate_corsika_histograms.py) into ecsv files. Multidimensional arrays are flattened (x and y coordinates for each element in the 2D histograms are passed at each row);
- One ecsv file is saved per histogram.

**Goal:** Change the format of the corsika output histograms to hd5 format. The hd5 format allows us to save multidimensional histograms, while the ecsv format allows only 2D arrays.

**Method:** 
- Since we already use astropy QTables, the change of format is expect to be rather simple. 
- Instead of having one hd5 file per histogram, I will allow the application to write the output of all the histograms into a single hd5 file, which is a cleaner solution and would not pollute the output directory with a multitude of files.

Please @GernotMaier @orelgueta, let me know if you are happy with this solution or if you have different ideas. Thank you.

**Comment by VictorBarbosaMartins** [comment]
I started updating the code according to the procedure described above. The function for exporting to hd5 is an astropy one ([astropy.io.misc)](https://docs.astropy.org/en/stable/io/misc.html) » write_table_hdf5) but requires the installation of the h5py package, which takes additionally 4.5 MB . Do you agree to add this package as a dependency?

**Comment by GernotMaier** [comment]
Yes, we will required this package a couple of times in future.

**Comment by kosack** [comment]
In case it helps, we also write a few of these histograms in ctapipe in the standard DL1/DL2 output format.  We found tthat astropy's HDF output was a bit annoying in how it works (storing metadata in a text block rather than in HDF5 attributes, and requiring H5py instead of pytables.  We therefore use the ctapipe io mechanisms to transform to HDF5.  ctapipe provides two mechanisms:
* `ctapipe.io.HDF5TableWriter`, which allow you to write single rows a a time by defining an appropriate Container class that defines the fields
* `ctapipe.io.write_table` which writes an AstroPy table directly

These properly handle all metadata and also allow for things like column transforms to handle things that are more complex.  

I would highly suggest using these, as otherwise we will end up with multiple non-standard formats.
