### ISSUE TITLE
Use read-only DB account in (some) tests

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#604]
Add unit / application test runs for read-only DB user.

**Comment by orelgueta** [comment]
Please allow me to clarify this issue a little. 
Right now we use the API user for tests because some tests require write rights. It would be good if only those tests would use the API user and all others use the read-only user. It is probably possible to implement two separate configurations for the DB access and then choose which to use in each test by passing the right fixture. In addition, we could add a decorator for the tests that require write permissions and run only if those permissions are available.

I am removing the `good first issue` label though since it's not so easy to start with (requires a bit more experience with pytest, fixtures, GitHub secrets, etc.). It is not a hard issue, just not something to start with I think.

**Comment by GernotMaier** [comment]
@orelgueta - let's discuss quickly how to do this.

I actually don't see an issue of running the unit tests with write permission. I think the main issue is that we don't test the code for read-only users.

However, if we want to run most unit tests with readonly:

- PR #711 allows to run unit tests now with readonly credential
- means that some tests in `test_db_handler.py` are skipped
- how would we want to run them? Change the CI-unittest workflow that it runs first on all tests with the read-only credential and then on test_db_handler again with the write credential? This would work, but probably would mess up the coverage report.

Alternative would be to define in `.env` both the read and write credential, and have in conftest.py a fixture `db_read` and `db_write` (picking the write environmental variables).

**Comment by GernotMaier** [comment]
Implementation plan:

- add new github secrets for readonly access of the DB (`SIMTOOLS_DB_READ_USER`, `SIMTOOLS_DB_READ_PW`)
- change in `conftest.py` the db and db_config methods to `db_config(access=[{'read_only': True}])`. Function returns read-only or write access credentials depending on the `access` parameter
- no changes required for tests which are reading only, writing unit tests will have set read_only to False

This should work for unit tests without larger problems.

For integration, we would have to separate read only and read/write tests - although I am not sure if we have at this point tests which are supposed to write.

@orelgueta - any thoughts on this approach?

**Comment by orelgueta** [comment]
This is more or less solved, no?

**Comment by GernotMaier** [comment]
Yes, this is solved and we can close it.
