### ISSUE TITLE
Delete unused function in simulator

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#728]
This is a continuation of the to-do list from #660.

I propose to delete the following function in simulator that is not being used:

https://github.com/gammasim/simtools/blob/fa72abffcde0b4224e044d76e5c28fa5581f4be4/simtools/simtel/simtel_histograms.py#L47-L57

This would mean also deleting `_plot_combined_histograms` and also `print_histograms`. Both functions are not used and for the generation of plots and pdfs we already have the `generate_simtel_array_histograms.py` application. Is there any problem to delete these that I am not aware of?

**Comment by orelgueta** [comment]
I am really surprised to see these functions are not used because I am 100% sure Raul had functionality to print sim_telarray histograms and I think it was within his `production.py` application. He even showed the histograms in some ASWG meeting.

However, if you have a better implementation, I don't have an objection to remove and replace this implementation.

**Comment by VictorBarbosaMartins** [comment]
The base functionality is the `plot_one_histogram` function from `simtel_histograms` which is kept. This function is also used by the application `generate_simtel_array_histograms` to produce the pdfs with the histograms. I think that is all we need. As the application already produces the histograms and save them to file, we dont need to do a similar thing in the module

**Comment by orelgueta** [comment]
OK, no problem then
