### ISSUE TITLE
Suggest to remove "yaml" as file suffix

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#768]
(we've discussed this somewhere else also, but can't find it)

When testing for file suffixes, we always test for `yml` and `yaml`, which is a bit cumbersome. We do nowhere use `yaml`, could we get rid of it? 

(not super important, just a little bit annoying)

**Comment by VictorBarbosaMartins** [comment]
We discussed this here https://github.com/gammasim/simtools/pull/763#discussion_r1441730688

I agree to remove the support to `.yaml` and keep only `.yml`

**Comment by orelgueta** [comment]
Actually, we should use `.yaml` everywhere rather than `.yml` (see [here](https://yaml.org/faq.html) and screenshot from wikipedia below). If we want to stick to just one, it should be the recommended one.

<img width="601" alt="image" src="https://github.com/gammasim/simtools/assets/22728856/0fc93f31-40ea-4b0c-bc87-ab8ed8140985">

**Comment by GernotMaier** [comment]
I really didn't want to start this discussion - the wikipedia article on yaml lists both suffixes. Also do a lot (most?) industry services  (gitlab, docker, ...) use yml.  I doesn't seem to be that there is a standard, more a choice.

<img width="1010" alt="Screenshot 2024-01-08 at 09 14 01" src="https://github.com/gammasim/simtools/assets/14001688/8e42f125-9798-4224-97c5-23dfeb75c4ca">

**Comment by orelgueta** [comment]
It is definitely a choice and won't make a difference. But since you opened this discussion, we might as well follow it through. 

It is true that you can find many places that use `.yml`, but it seems to be due to historic reasons (like Windows having issues with suffixes which are not 3 characters long). 
Since we are starting a new project, I don't see a reason not to follow the official recommendation from the YAML website (see the link in my previous comment)

<img width="338" alt="image" src="https://github.com/gammasim/simtools/assets/22728856/7586a051-f15f-4c41-bc5c-be1c55b6d2ba">

The same Wikipedia article you pasted also references that FAQ and states `yaml` should be preferred (screenshot in the previous comment).

Why choose `yml` over `yaml` then?

**Comment by GernotMaier** [comment]
Interesting read: https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml

Seems many more people nowadays are using `yml`. Anyway, I realize that this discussion is longer than adding the corresponding code to handle both (as long as we don't require to duplicate all test files in yml and yaml).

**Comment by orelgueta** [comment]
OK, so we can close this =)

**Comment by GernotMaier** [comment]
I used grep to find typical statements checking for file endings to check that they are all something like:
```
if Path(metadata_file_name).suffix in (".yaml", ".yml", ".json")
```

to cover yaml and yml.

To be absolute consistent, we should add `yaml` probably to this line?

https://github.com/gammasim/simtools/blob/7cfbe595c005bbdaa2f39ffb1b23e2698d83b250/simtools/db_handler.py#L49

Otherwise I think we are good and could close this issue.
