### ISSUE TITLE
Error bars

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#79]
(With the danger that you take away my github account, I'll continue starting issues, even for minor stuff)

Noticed that we have to think as well about error bars.

Looking at the following plot make me think that there are some missing? Would that be difficult?

![validate_optics_North-LST-1_eff_area](https://user-images.githubusercontent.com/14001688/95253613-ee00c100-081e-11eb-8f3d-27c6437918ca.png)

Same for effective focal length, d80, ...

**Comment by RaulRPrado** [comment]
I agree.
The difficulty really depends on the specifics of each plot.
In this case, the eff area comes from a fraction of photons detected/simulated. A binomial uncertainty should give what we want.
I'll implement that.

It's important to note that it won't always be so easy nor worth it. In this case, the eff area is basically flat, which makes very small fluctuations look so ugly. If the error calculation here was complicated, I'd say it's not worth it because it's in general very small.

**Comment by GernotMaier** [comment]
Agree - don't put a huge amount of work into it. I didn't notice the very suppressed y-axis, which amplifies the flucutations.

Errors bars should be wherever they make sense and can be achieved with reasonable effort.

**Comment by RaulRPrado** [comment]
Ok.

I think it's better to implement this ones later. I'll finish going through the documentation issues first.

**Comment by orelgueta** [comment]
I can help implementing error bars here if you wish. Also, I am not sure the fluctuations are that small (1-2 m^2 is non-negligible no?).

**Comment by GernotMaier** [comment]
Orel is actually right - where does the uncertainty of 1 m^2 come from? Although this is a ray-tracing experiment, the result should be almost deterministic. Of course we should see partly the imprint of the structure / beams etc.

**Comment by orelgueta** [comment]
You don't see the imprint of the structure because we do not simulate it in sim_telarray. To include it we use the telescope transmission function, but for the LST (which is what I assume is simulated, should add a label to the plot), that function is flat.
However, shouldn't we see the imprint of the camera? That we do simulate I think.

**Comment by GernotMaier** [comment]
I suggest to close this issue. 

The requirement on having uncertainties on all results is a generic task and written down in the requirements and concept document.
